# Generated by Django 2.2.4 on 2021-04-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.TextField(default='trip plan'),
        ),
    ]
